services:

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lms12345
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: pasupunuti26/lms-be:latest
    container_name: lms-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:lms12345@postgres:5432/postgres
      PORT: 8080
      MODE: production
    ports:
      - "8080:8080"

  frontend:
    image: pasupunuti26/lms-fe:latest
    container_name: lms-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
